# --- 1. DOMINIO: SALONES (RECURSOS ESTATICOS) ---

# Mantener la lista de salones como está.
SALONES_DISPONIBLES = [
    'A214', 'A215', 'A216', 'A8118', 'A8120', 'A8117', 
    'A8119', 'A11201', 'A8121', 'A504', 'A205', 'A213', 
    'A211', 'A505', 'A506', 'A507', 'A212', 'A11202', 
    'A203', 'CCSAL5', 'CCSAL7', 'CCSAL1', 'A11203', 
    'CLOUD', 'CCSAL9', 'A11204', 'A325', 'A1023'
]


# --- 2. DOMINIO: PROFESORES POR MATERIA (OPCIONES) ---

PROFES_POR_MATERIA = {
    'ALGEBRA': [
        'ORTIZ CORDERO GABRIEL', 'HERNANDEZ LOPEZ SERGIO', 
        'VIEYRA REBOYO LUIS ARMANDO', 'RAMIREZ LAZOS ESTEBAN'
    ],
    
    'CALCULO DIFERENCIAL E INTEGRAL': [
        'VERDE CRUZ ABEL', 'GONZALEZ HERNANDEZ GERARDO', 
        'RAMIREZ LAZOS ESTEBAN', 'PELCASTRE RAMIREZ GLORIA SAMANTHA', 
        'HERNANDEZ GALICIA SALOMON', 'RODRIGUEZ GARCIA ARTURO'
    ],
    
    'DISEÃ‘O LOGICO (L)': [ 
        'BERNAL DIAZ ARCELIA', 'LOZANO MENDEZ EFREN', 
        'GONZALEZ MAXINEZ DAVID JAIME', 'RAMIREZ CRUZ JOSE LUIS', 
        'LOPEZ CARRETO JUAN MANUEL', 'ARELLANO RIVERA ESTEBAN', 
        'PATIÑO RODRIGUEZ RAMON'
    ],
    'DISEÃ‘O Y ANALISIS DE ALGORITMOS': [ 
        'PEREZ MEDEL MARCELO', 'OLIVER MORALES CARLOS', 
        'SANCHEZ HERNANDEZ MIGUEL ANGEL', 'SANCHEZ SANCHEZ VICTOR MANUEL', 
        'HERNANDEZ CABRERA JESUS', 'CAMACHO ALVAREZ JUAN CARLOS', 
        'QUIROZ ALMARAZ SERGIO'
    ],
    'DISEÃ‘O DE SISTEMAS DIGITALES (L)': [ 
        'HERNANDEZ HERNANDEZ MARTIN', 'GONZALEZ MAXINEZ DAVID JAIME', 
        'LOZANO MENDEZ EFREN'
    ],
    
    'COMPUTADORAS Y PROGRAMACION': [
        'PEÑALOZA ROMERO ERNESTO', 'GASTALDI PEREZ JUAN', 'HERNANDEZ CABRERA JESUS', 
        'SANCHEZ SANCHEZ VICTOR MANUEL', 'CANDELARIO ALAVEZ JORGE LUIS', 'RAMOS MARQUEZ JUAN CARLOS'
    ],
    'GEOMETRIA ANALITICA': [
        'MARTINEZ ROMERO JONATHAN', 'VIEYRA REBOYO LUIS ARMANDO', 'PATIÑO RODRIGUEZ RAMON', 
        'GONZALEZ BETANCOURT RAFAEL', 'RODRIGUEZ GARCIA ARTURO', 'SOLIS ALCANTAR EVERARDO'
    ],
    'INTRODUCCION A LA INGENIERIA EN COMPUTACION': [
        'VELASCO AGUSTIN AARON', 'CANDELARIO ALAVEZ JORGE LUIS', 'ARELLANO OROZCO JUAN MANUEL', 
        'PARRALES CASTAÑEDA CARLOS ALBERTO', 'GRADA HUERTA IVAN'
    ],
    'ALGEBRA LINEAL': [
        'PEREZ GUZMAN ALEJANDRO', 'FALCON ARELLANO BERENICE ITZEL', 'SOLIS ALCANTAR EVERARDO'
    ],
    'CALCULO VECTORIAL': [
        'GONZALEZ HERNANDEZ GERARDO', 'RODRIGUEZ GARCIA ARTURO', 'RAMIREZ LAZOS ESTEBAN', 
        'SANCHEZ MORALES VICTOR MANUEL'
    ],
    'COMUNICACION': [
        'MONDRAGON ESCOBAR ALFREDO', 'GUTIERREZ CASTILLO ALMA ROSA', 'ISLAS HERNANDEZ CLARA YAHAIRA', 
        'ALMANZAR VAZQUEZ MARIA GUADALUPE'
    ],
    'EMPRENDIMIENTO 1': [
        'FERIA VICTORIA MARIA ANGELICA', 'ROMERO ANDALON JESUS ANGEL', 'COLUNGA VAZQUEZ MATILDE'
    ],
    'PROGRAMACION ORIENTADA A OBJETOS': [
        'CANDELARIO ALAVEZ JORGE LUIS', 'CRUZ LUEVANO BLANCA ESTELA'
    ],
    'TALLER DE CREATIVIDAD E INNOVACION': [
        'PEREZ VALDES JOEL ALFREDO', 'CHIAPA MONROY CUAUHTEMOC', 'ABURTO CAMACHO BLANCA PAMELA'
    ],
    'ECUACIONES DIFERENCIALES': [
        'GONZALEZ HERNANDEZ GERARDO', 'BLANCO BAUTISTA ROBERTO', 'MARTINEZ ROMERO JONATHAN', 
        'VERDE CRUZ ABEL', 'JUAREZ PALMA JOSE GIL', 'GONZALEZ BETANCOURT RAFAEL', 'RODRIGUEZ GARCIA ARTURO'
    ],
    'ELECTRICIDAD Y MAGNETISMO (L)': [
        'HERNANDEZ LOPEZ SERGIO', 'SUAREZ HERRERA ALEJANDRO', 'PICCINELLI BOCCHI GABRIELLA', 
        'VERDE CRUZ ABEL', 'SEGURA RAUDA MINERVA', 'ALVAREZ SORIANO MANUEL ALEJANDRO', 'PEREZ GUZMAN ALEJANDRO'
    ],
    'EMPRENDIMIENTO 2': [
        'GARCIA VILLANUEVA MA. DEL PILAR', 'MONDRAGON ESCOBAR ALFREDO', 'GUTIERREZ CASTILLO ALMA ROSA', 
        'COLUNGA VAZQUEZ MATILDE', 'REYES TECONTERO NORMA'
    ],
    'ESTRUCTURA DE DATOS': [
        'SANCHEZ HERNANDEZ MIGUEL ANGEL', 'BLANCO BAUTISTA ROBERTO', 'PEÑALOZA ROMERO ERNESTO', 
        'CRUZ LUEVANO BLANCA ESTELA', 'HERNANDEZ CABRERA JESUS', 'SANCHEZ SANCHEZ VICTOR MANUEL'
    ],
    'METODOS NUMERICOS': [
        'MARTINEZ ROMERO JONATHAN', 'PEREZ GUZMAN ALEJANDRO', 'BLANCO BAUTISTA ROBERTO', 
        'VIEYRA REBOYO LUIS ARMANDO', 'GONZALEZ BETANCOURT RAFAEL', 'MORALES GONZALEZ JORGE CARLOS', 
        'RAMIREZ LAZOS ESTEBAN'
    ],
    'PROBABILIDAD Y ESTADISTICA': [
        'HERNANDEZ LOPEZ SERGIO', 'TORRES TORRES FAUSTO', 'PELCASTRE RAMIREZ GLORIA SAMANTHA'
    ],
    'BASES DE DATOS 1': [
        'ORDOÑEZ ROSALES MARTIN', 'SOBERANES JAIME ROBERTO MISAEL'
    ],
    'DISPOSITIVOS ELECTRONICOS (L)': [
        'ORTEGA NAVA CARLOS FERNANDO', 'ALVAREZ SORIANO MANUEL ALEJANDRO', 'LOPEZ CARRETO JUAN MANUEL'
    ],
    'EMPRENDIMIENTO 3': [
        'GARCIA VILLANUEVA MA. DEL PILAR', 'CERVANTES PATIÑO MOISES'
    ],
    'MATEMATICAS DISCRETAS': [
        'ORTIZ CORDERO GABRIEL', 'RODRIGUEZ GARCIA ARTURO'
    ],
    'ADMINISTRACION DE PROYECTOS': [
        'REYES CRUZ ANA CLAUDIA', 'MONDRAGON ESCOBAR ALFREDO', 'GONZALEZ AYALA LUIS ENRIQUE', 
        'ROMERO ANDALON JESUS ANGEL', 'ALBA VILLA BELEN ANAID', 'VIDAL CASTRO RICARDO ADOLFO', 
        'GUERRERO SANTAMARIA EFREN'
    ],
    'LENGUAJES FORMALES-AUTOMATAS': [
        'SANCHEZ SANCHEZ VICTOR MANUEL', 'OLIVER MORALES CARLOS', 'JUAREZ ROBLES ELIZABETH', 
        'ORTIZ CORDERO GABRIEL', 'CAMPOS BRAVO JORGE IVAN'
    ],
    'PROGRAMACION WEB 1': [
        'CANDELARIO ALAVEZ JORGE LUIS', 'VELASCO AGUSTIN AARON', 'ORTIZ JIMENEZ MARIA ELENA', 
        'CAMACHO ALVAREZ JUAN CARLOS', 'PEREZ PAZ EDUARDO'
    ],
    'COMPILADORES': [
        'ORDOÑEZ ROSALES MARTIN', 'CORDERO ORTIZ GABRIEL', 'PEREZ MEDEL MARCELO', 
        'GUTIERREZ OROZCO RICARDO ARTURO'
    ],
    'INGENIERIA DE SOFTWARE': [
        'GONZALEZ HERNANDEZ MARIA GABRIELA', 'CAMACHO ALVAREZ JUAN CARLOS', 'CRUZ LUEVANO BLANCA ESTELA'
    ],
    'SISTEMAS OPERATIVOS': [
        'VAZQUEZ MORALES RODOLFO', 'GONZALEZ HERNANDEZ MARIA GABRIELA', 'AYALA PEÑA ESTEBAN'
    ],
    'MICROPROCESADOR.Y MICROCONTROLAD.(L)': [
        'BERNAL DIAZ ARCELIA', 'GONZALEZ MAXINEZ DAVID JAIME', 'CANDELARIO ALAVEZ JORGE LUIS', 
        'HERNANDEZ CONTRERAS JUAN MANUEL', 'LOZANO MENDEZ EFREN', 'OCAMPO ALVAREZ ARTURO', 
        'MARTINEZ ROMERO JONATHAN'
    ],
    'PROGRAMACION WEB 2': [
        'SANCHEZ SANCHEZ VICTOR MANUEL', 'SANCHEZ HERNANDEZ MIGUEL ANGEL', 'VERDUZCO RODRIGUEZ MARIANA', 
        'VELASCO AGUSTIN AARON', 'RAMOS MARQUEZ JUAN CARLOS'
    ],
    'REDES DE COMPUTADORAS 1 (L)': [
        'HERNANDEZ CABRERA JESUS', 'GALICIA RANGEL GILDA', 'GARCIA MONROY JOSE ANTONIO', 
        'QUINTERO CERVANTES JOSE MANUEL', 'PEREZ MUÑOZ ANTONIO GERARDO', 'GARCIA GUZMAN ENRIQUE', 
        'ANAYA MANILA DZOARA IVETTE', 'TORRES RODRIGUEZ GERARDO'
    ],
    'SISTEMAS DE INFORMACION': [
        'GUTIERREZ OROZCO RICARDO ARTURO', 'MENDOZA GONZALEZ OMAR', 'CANDELARIO ALAVEZ JORGE LUIS', 
        'VERDUZCO RODRIGUEZ MARIANA', 'VELASCO AGUSTIN AARON', 'CRUZ LUEVANO BLANCA ESTELA'
    ],
    'BASES DE DATOS 2': [
        'GERMAN ROSAS CESAR FRANCISCO', 'MENDOZA GONZALEZ OMAR', 'SOBERANES JAIME ROBERTO MISAEL'
    ],
    'HABILIDADES DIRECTIVAS': [
        'FERIA VICTORIA MARIA ANGELICA', 'GARIBAY PEDRAZA ALMA LILIA', 'UGALDE LOPEZ JUDITH', 
        'GUERRERO SANTAMARIA EFREN', 'REYES TECONTERO NORMA'
    ],
    'PROGRAMACION MOVIL 1': [
        'CAMACHO ALVAREZ JUAN CARLOS', 'GUTIERREZ LOPEZ FELIPE DE JESUS'
    ],
    'REDES DE COMPUTADORAS 2': [
        'GARCIA GUZMAN ENRIQUE', 'GARCIA MONROY JOSE ANTONIO', 'TORRES RODRIGUEZ GERARDO', 
        'QUIROZ ALMARAZ SERGIO'
    ],
    'INTELIGENCIA ARTIFICIAL': [
        'ROMERO UGALDE MARTIN MANUEL', 'OLIVER MORALES CARLOS', 'JUAREZ ROBLES ELIZABETH', 
        'MONTERROSA ESCOBAR AMILCAR AMADO', 'MORALES PALAFOX EDGAR'
    ],
    'MINERIA DE DATOS': [
        'SANCHEZ HERNANDEZ MIGUEL ANGEL', 'MENDOZA GONZALEZ OMAR', 'CANTO GALLO RAFAEL', 
        'JUAREZ ROBLES ELIZABETH', 'GOYTIA HERRERA MARCO INTI'
    ],
    'SEGURIDAD INFORMATICA': [
        'VAZQUEZ MORALES RODOLFO', 'NERIA OROZCO ERIK DE JESUS', 'HERNANDEZ AUDELO LEOBARDO', 
        'VERDUZCO RODRIGUEZ MARIANA', 'NAVARRO DIAZ RAMON', 'PALMA LOPEZ DANIEL FERNANDO', 
        'AGUILAR HERNANDEZ JOSE FRANCISCO', 'SOBERANES JAIME ROBERTO MISAEL'
    ],
    'GRAFICACION POR COMPUTADORA': [
        'GONZALEZ AYALA LUIS ENRIQUE', 'SALGADO RODRIGUEZ JOSE FRANCISCO', 'HERNANDEZ CERVANTES LILIANA'
    ],
    'INSTRUMENTACION Y CONTROL': [
        'ZUÑIGA VILLEGAS BENITO', 'GARCIA GUZMAN ENRIQUE'
    ],
    'INTERNET DE LAS COSAS': [
        'LOZANO MENDEZ EFREN'
    ],
    'PROYECTO ESCUELA-INDUSTRIA': [
        'FLORES DIAZ IMELDA DE LA LUZ', 'MONDRAGON ESCOBAR ALFREDO', 'HERNANDEZ AGUILAR CESAR ALBERTO', 
        'COLUNGA VAZQUEZ MATILDE', 'COVARRUBIAS RODRIGUEZ FERNANDO ROBERTO', 'CRUZ ROSALES ERNESTO'
    ],
    'TEMAS ESPECIALES DE BASES DE DATOS': [
        'ORDOÑEZ ROSALES MARTIN', 'GERMAN ROSAS CESAR FRANCISCO'
    ],
    'TEMAS ESPECIALES DE COMPUTACION 2': [
        'AVILA GARCIA JOSE ANTONIO', 'VALENZUELA RAMOS JUAN GERMAN'
    ],
    'TEMAS ESPECIALES DE COMPUTACION 6': [
        'VEGA MUNGUIA ELIO', 'SALGADO RODRIGUEZ JOSE FRANCISCO'
    ],
    'TEMAS ESPECIALES DE PROGRAMACION 2': [
        'PEREZ SANCHEZ HIRAM EMMANUEL', 'SALDAÑA ALDANA HECTOR'
    ],
    'VINCULACION EMPRESARIAL': [
        'PEREZ VALDES JOEL ALFREDO', 'RIVERO PICAZO MARIELA VIANEY'
    ],
    'TEMAS ESPECIALES DE COMPUTACION 1': [
        'FLORES DIAZ IMELDA DE LA LUZ', 'ALMANZAR VAZQUEZ MARIA GUADALUPE', 'VALENZUELA LOPEZ RODOLFO'
    ],
    'TEMAS ESPECIALES DE COMPUTACION 3': [
        'VILLANUEVA ORTEGA JUAN ANTONIO', 'SALGADO RODRIGUEZ JOSE FRANCISCO'
    ],
    'PROGRAMACION DE VIDEOJUEGOS 2': [
        'SALGADO RODRIGUEZ JOSE FRANCISCO'
    ],
    'ROBOTICA': [
        'GONZALEZ MAXINEZ DAVID JAIME', 'CASTRO DIAZ JOSE DANIEL'
    ],
    'SEMINARIO INGENIERIA EN COMPUTACION': [
        'PEREZ VALDES JOEL ALFREDO', 'CANO SANTOS BERENICE'
    ],
    'PROGRAMACION DE VIDEOJUEGOS 1': [
        'SALGADO RODRIGUEZ JOSE FRANCISCO'
    ],
    'TEMAS ESPECIALES DE REDES': [
        'QUINTERO CERVANTES JOSE MANUEL', 'TORRES RODRIGUEZ GERARDO'
    ],
    'PROCESAMIENTO DIGIT.IMAGENES': [
        'GONZALEZ PONCE ALEJANDRO RENE'
    ],
    'TEMAS ESPECIALES DE COMPUTACION 4': [
        'ESCONDRILLAS MAYA CARLOS'
    ],
    'TEMAS ESPECIALES DE SEGURIDAD INFORM': [
        'HERNANDEZ AUDELO LEOBARDO'
    ],
    'ADMINISTRACION SISTEMAS MULTIUSUAR': [
        'LOPEZ HERNANDEZ JORGE ARTURO'
    ],
    'SISTEMAS EXPERTOS': [
        'ROMERO UGALDE MARTIN MANUEL.'
    ]
}


# --- 3. DOMINIO: REGLAS DE TIEMPO Y BLOQUES ---

# Esta estructura define los días y la duración de cada patrón
PATRONES_INFO = {
    'M-J': {
        'dias': ['Martes', 'Jueves'],
        'duracion_horas': 2.0
    },
    'L-M-V': {
        'dias': ['Lunes', 'Miercoles', 'Viernes'],
        'duracion_horas': 1.5
    },
    'SABADO': { 
        'dias': ['Sabado'],
        'duracion_horas': 4.0
    },
    'Indefinido': {
        'dias': [],
        'duracion_horas': 0
    }
}

# Diccionario unificado de bloques: { (Turno, Patrón): [Lista de Bloques] }
# Esto hace que la función obtener_bloques_para sea mucho más simple
BLOQUES_HORARIOS = {
    # Turno Matutino (M)
    ('M', 'M-J'): ['07:00-09:00', '09:00-11:00', '11:00-13:00'],
    ('M', 'L-M-V'): ['07:00-08:30', '08:30-10:00', '10:00-11:30', '11:30-13:00'],
    ('M', 'SABADO'): ['07:00-11:00', '11:00-15:00'],

    # Turno Vespertino (V)
    ('V', 'M-J'): ['13:00-15:00', '15:00-17:00', '17:00-19:00', '19:00-21:00'],
    ('V', 'L-M-V'): ['13:00-14:30', '14:30-16:00', '16:00-17:30', '17:30-19:00', '19:00-20:30']
}


# --- 4. FUNCIÓN AUXILIAR SIMPLIFICADA ---

def obtener_bloques_para(turno, patron):
    """
    Retorna la lista correcta de bloques de horario según el turno y el patrón,
    utilizando una búsqueda directa en el diccionario.
    """
    # Si la tupla (turno, patron) no existe, retorna una lista vacía por defecto
    return BLOQUES_HORARIOS.get((turno, patron), [])


if __name__ == "__main__":
    print("--- Base de Conocimiento Cargada ---")
    
    print(f"\nSalones Disponibles ({len(SALONES_DISPONIBLES)}):")
    print(SALONES_DISPONIBLES[:3])
    
    print(f"\nReglas de Profesores ({len(PROFES_POR_MATERIA)} materias):")
    print(f"Opciones para DISEÑO LOGICO (L): {PROFES_POR_MATERIA.get('DISEÑO LOGICO (L)', 'No definido')}")
    
    print("\nReglas de Tiempo:")
    print(f"Bloques para Matutino M-J: {obtener_bloques_para('M', 'M-J')}")
    print(f"Bloques para Vespertino L-M-V: {obtener_bloques_para('V', 'L-M-V')}")
    print(f"\nBloques para Sabado M: {obtener_bloques_para('M', 'SABADO')}")